Vagrant.configure("2") do |config|
  nodes = [
    { :name => "mariadb20", :ip => "192.168.56.20" },
    { :name => "mariadb21", :ip => "192.168.56.21" },
    { :name => "mariadb22", :ip => "192.168.56.22" }
  ]

  nodes.each do |node|
    config.vm.define node[:name] do |node_config|
      node_config.vm.box = "rockylinux/9"
      node_config.vm.hostname = node[:name]
      node_config.vm.network "private_network", ip: node[:ip]

      node_config.vm.provider "virtualbox" do |vb|
        vb.name = node[:name]
        vb.memory = 4096
        vb.cpus = 2
      end

      node_config.vm.provision "shell", inline: <<-SHELL
        dnf install -y mariadb-server
        systemctl enable mariadb
        systemctl start mariadb
      SHELL
    end
  end
end
