Vagrant.configure("2") do |config|
  # ✅ Rocky Linux 8 사용
  config.vm.box = "rockylinux/9"
  config.disksize.size = '20GB'

  # VM 이름 설정
  config.vm.define "oracle21c" do |oracle|
    oracle.vm.hostname = "oracle21c"

    # 네트워크 설정 (고정 IP)
    oracle.vm.network "private_network", ip: "192.168.56.10"

    # VirtualBox 설정
    oracle.vm.provider "virtualbox" do |vb|
      vb.name = "oracle21c"
      vb.memory = "4096"
      vb.cpus = 2
    end

    config.vm.synced_folder ".", "/vagrant", disabled: true

    # 프로비저닝 (Oracle 21c XE 설치)
    oracle.vm.provision "shell", inline: <<-SHELL
      echo "=====[ 1. resize disk ]====="
      sudo yum clean all
      sudo yum -y update
      sudo yum install cloud-utils-growpart -y
      sudo growpart /dev/sda 4
      sudo xfs_growfs /
      echo "=====[ 1. 패키지 업데이트 및 필수 라이브러리 설치 ]====="
      sudo yum -y install wget
      sudo systemctl stop firewalld
      sudo systemctl disable firewalld
      sudo systemctl status firewalld

      # 의존 패키지 설치
      sudo wget https://dl.rockylinux.org/pub/rocky/8/AppStream/x86_64/os/Packages/c/compat-openssl10-1.0.2o-4.el8_6.x86_64.rpm
      sudo dnf -y localinstall compat-openssl10-1.0.2o-4.el8_6.x86_64.rpm

      # 사전 설치 파일 다운로드
      sudo curl -o oracle-database-preinstall-21c-1.0-1.el8.x86_64.rpm https://yum.oracle.com/repo/OracleLinux/OL8/appstream/x86_64/getPackage/oracle-database-preinstall-21c-1.0-1.el8.x86_64.rpm
	  sudo dnf -y localinstall oracle-database-preinstall-21c*

      # 설치 파일 실행
      # -L 옵션 : Redirect (301, 302)가 응답될 경우, redirect 된 링크로 가서, 파일을 다운로드 받음
      sudo curl -L -o oracle-database-xe-21c-1.0-1.ol8.x86_64.rpm https://download.oracle.com/otn-pub/otn_software/db-express/oracle-database-xe-21c-1.0-1.ol8.x86_64.rpm
      sudo dnf -y localinstall oracle-database-xe-21c*

      echo "========== Configuring Oracle XE with auto password =========="
      sudo yum install expect -y
    expect <<EOF
    spawn sudo /etc/init.d/oracle-xe-21c configure
    expect "Enter SYS user password:"
    send "Oracle123!\r"
    expect "Confirm the password:"
    send "Oracle123!\r"
    expect eof
    EOF

    echo "========== Setting up environment variables =========="
    echo "export ORACLE_BASE=/opt/oracle" | sudo tee -a /etc/profile
    echo "export ORACLE_HOME=\$ORACLE_BASE/homes/OraDB21Home1" | sudo tee -a /etc/profile
    echo "export PATH=\$ORACLE_HOME/bin:\$PATH" | sudo tee -a /etc/profile
    source /etc/profile

    echo "========== Enabling Oracle service =========="
    sudo systemctl enable oracle-xe-21c
    sudo systemctl start oracle-xe-21c

    echo "========== Checking Oracle service status =========="
    sudo systemctl status oracle-xe-21c --no-pager

    echo "========== Oracle XE 21c Installation Completed! =========="

    SHELL
  end
end
